### PR TITLE
Remove undefined functions declared in headers

### PR DESCRIPTION
**Pull request by Diviloper**
This PR removes some functions declared in `meos_internal.h` that are not defined anywhere in the code.
They are mostly functions that used to exist whose declaration was not removed since they don't cause an error.

### CODE REVIEW

**Comment by Diviloper** [comment]
@estebanzimanyi @mschoema in this PR I was also going to remove some duplicated declarations present in the header files. However, maybe the duplications are intended, as many are present in different "groups" of functions, so I wanted to make sure. For example, the `*_compact` functions in `meos_internal.h` are declared both in the [`Transformation functions for temporal types`](https://github.com/MobilityDB/MobilityDB/blob/d30f545a90685a578656d214c08a38a237bd9e68/meos/include/meos_internal.h#L728) group and in the [`Compact functions for final append aggregate`](https://github.com/MobilityDB/MobilityDB/blob/d30f545a90685a578656d214c08a38a237bd9e68/meos/include/meos_internal.h#L1010) group.
Can you confirm whether this duplication is actually desired? Otherwise I will also remove these duplications.

**Comment by estebanzimanyi** [comment]
These duplications are not intended
Thanks for pointing out this !

________________________________
De : Víctor Diví ***@***.***>
Envoyé : lundi 12 août 2024 00:36
À : MobilityDB/MobilityDB ***@***.***>
Cc : ZIMANYI Esteban ***@***.***>; Mention ***@***.***>
Objet : Re: [MobilityDB/MobilityDB] Remove undefined functions declared in headers (PR #560)


@estebanzimanyi<https://github.com/estebanzimanyi> @mschoema<https://github.com/mschoema> in this PR I was also going to remove some duplicated declarations present in the header files. However, maybe the duplications are intended, as many are present in different "groups" of functions, so I wanted to make sure. For example, the *_compact functions in meos_internal.h are declared both in the Transformation functions for temporal types<https://github.com/MobilityDB/MobilityDB/blob/d30f545a90685a578656d214c08a38a237bd9e68/meos/include/meos_internal.h#L728> group and in the Compact functions for final append aggregate<https://github.com/MobilityDB/MobilityDB/blob/d30f545a90685a578656d214c08a38a237bd9e68/meos/include/meos_internal.h#L1010> group.
Can you confirm whether this duplication is actually desired? Otherwise I will also remove these duplications.

**Comment by Diviloper** [comment]
Great! There shouldn't be any duplicated declaration now.
I've left the declaration in the group where I thought fit best, but you may want to review it.

**Review by mschoema — APPROVED** [review]

**Comment by mschoema** [comment]
Looks good, thanks for the PR

**Pull request merged**
