### PR TITLE
Check Creative Commons license

### PR DESCRIPTION
**Pull request by estebanzimanyi**

### CODE REVIEW

**Comment by estebanzimanyi** [comment]
For testing purposes I temporarily removed a license in one file and a copyright in another. The result is as follows
```
esteban@DESKTOP-9FBND60:~/src/PR/MobilityDB$ tools/scripts/test_license.sh
 ****************************************************
 *** Found documentation files without copyright
 ****************************************************
doc/data_generator.xml: *No copyright* UNKNOWN
 ****************************************************
 *** Found documentation files without valid license headers
 ****************************************************
doc/manipulating_box_types.xml
```

**Comment by cvvergara** [comment]
The coveralls are failing.

**Comment by estebanzimanyi** [comment]
This is a floating point error in the coverage calculation. As you know, we haven't modified the C code for a month or so and the coverage continuously oscillates up and down a small fraction of a percentage. We cannot do anything about it.

**Review by cvvergara — APPROVED** [review]

**Comment by cvvergara** [comment]
Ah yeah, forgot that detail, well its been approved.

**Pull request merged**
