### PR TITLE
Add target doc

### PR DESCRIPTION
**Pull request by estebanzimanyi**

### CODE REVIEW

**Comment by estebanzimanyi** [comment]
I think we need to abandon the EPUB format unless there is a better tool than dbtoepub. There are many issues in the generated epub manual. I am looking whether there is an alternative.

**Comment by cvvergara** [comment]
```
doc/images/srf.vsd: *No copyright* UNKNOWN
```

**Comment by estebanzimanyi** [comment]
I have sent an email to the OASIS mailing list for docbook
https://lists.oasis-open.org/archives/docbook-apps/202108/msg00000.html
I have also solved the license problem

**Review by cvvergara — APPROVED** [review]
Cool, looks that you are advancing on the documentation

**Pull request merged**
