### PR TITLE
Adding actions to check licenses and shell script

### PR DESCRIPTION
**Pull request by cvvergara**
This adds action checks on:
* licenses
* shell code
Following the same work done on pgRouting in the last week

As you can see here:
https://github.com/cvvergara/MobilityDB/runs/1370853374?check_suite_focus=true
Many files lack license
and from here:
https://github.com/cvvergara/MobilityDB/runs/1370853365?check_suite_focus=true
There are not so many shell warnings

After merging change `tools/scripts/test_license.sh` needs to be updated to the licenses needs.
For example right now it tests for license in `src, `include and `points` directories
And for the documentation what is there is what I use for pgRouting (I find .rst which you don't use), because `licensecheck` does not find Creative Commons, I just find it, and using `licensecheck` to find the copyright

### CODE REVIEW

**Comment by cvvergara** [comment]
The license check works now:
 ```
 ****************************************************
 *** Found source files without valid license headers
 ****************************************************
npoint/src/datagen/create_test_tables_tnpoint.sql: *No copyright* UNKNOWN
 ****************************************************
 *** Found documentation files without copyright
 ****************************************************
doc/data_generator.xml: *No copyright* UNKNOWN
doc/introduction.xml: *No copyright* UNKNOWN
doc/manipulating_box_types.xml: *No copyright* UNKNOWN
doc/manipulating_temporal_types.xml: *No copyright* UNKNOWN
doc/mobilitydb-manual.xml: *No copyright* UNKNOWN
doc/reference.xml: *No copyright* UNKNOWN
doc/temporal_network_points.xml: *No copyright* UNKNOWN
doc/temporal_types.xml: *No copyright* UNKNOWN
doc/time_types_range_types.xml: *No copyright* UNKNOWN
doc/tnpoint_reference.xml: *No copyright* UNKNOWN
```
Of course the test is failing because the documentation files do not have a license (Creative Commons).
Each file must contain a license.

And the file npoint/src/datagen/create_test_tables_tnpoint.sql do not have a license

This action will help you to not forget to add licenses to files

**Comment by cvvergara** [comment]
The shell checker is also failing:
https://github.com/MobilityDB/MobilityDB/runs/3106364890?check_suite_focus=true#step:4:5
There are some issues that need to be addressed on
doc/install.sh

**Comment by estebanzimanyi** [comment]
> Of course the test is failing because the documentation files do not have a license (Creative Commons).
> Each file must contain a license.

After some search I have not found an example of how to add such a license to docbook (xml) source files. Could you please provide me a suggestion ?

**Comment by cvvergara** [comment]
In pgRouting or OSGeoLive we use sphinx comment for example:
https://raw.githubusercontent.com/pgRouting/pgrouting/main/doc/coloring/coloring-family.rst
I do not know docbook.

https://linux.die.net/man/1/licensecheck

**Comment by cvvergara** [comment]
Maybe something like:
```
 <?xml 
   ****************************************************************************
    MobilityDB Manual
    Copyright(c) MobilityDB Contributors

    This documentation is licensed under a Creative Commons Attribution-Share
    Alike 3.0 License: https://creativecommons.org/licenses/by-sa/3.0/
   ****************************************************************************
?>
```

**Comment by cvvergara** [comment]
I'll put my PR as draft, and un draft it when the issues are addressed

**Comment by cvvergara** [comment]
btw, I do not understand why the coverage/coveralls is decreased if I am not touching any of your code

**Comment by estebanzimanyi** [comment]
This is a rounding error in how the coverage is computed !

We are continuously having this issue that the coverage goes up and down
some decimals without touching the code :-(

**Comment by estebanzimanyi** [comment]
Alas it doesn't work. I have tried with an XML comment


and the generation of the documentation work.

However, I don't know whether this will be detected by the license checker
...

**Comment by cvvergara** [comment]
push your branch where you made the change, give me the link

**Comment by estebanzimanyi** [comment]
> push your branch where you made the change, give me the link

https://github.com/estebanzimanyi/MobilityDB/commit/231a00b0471f3f734e2c1bee32f92752133c91a8

**Comment by cvvergara** [comment]
before:
```
doc/data_generator.xml: *No copyright* UNKNOWN
doc/introduction.xml: *No copyright* UNKNOWN
doc/manipulating_box_types.xml: *No copyright* UNKNOWN
doc/manipulating_temporal_types.xml: *No copyright* UNKNOWN
doc/mobilitydb-manual.xml: *No copyright* UNKNOWN
doc/reference.xml: *No copyright* UNKNOWN
doc/temporal_network_points.xml: *No copyright* UNKNOWN
doc/temporal_types.xml: *No copyright* UNKNOWN
doc/time_types_range_types.xml: *No copyright* UNKNOWN
doc/tnpoint_reference.xml: *No copyright* UNKNOWN
```
after
```
tools/scripts/test_license.sh
 ****************************************************
 *** Found documentation files without copyright
 ****************************************************
doc/data_generator.xml: *No copyright* UNKNOWN
doc/introduction.xml: *No copyright* UNKNOWN
doc/manipulating_box_types.xml: *No copyright* UNKNOWN
doc/manipulating_temporal_types.xml: *No copyright* UNKNOWN
doc/reference.xml: *No copyright* UNKNOWN
doc/temporal_network_points.xml: *No copyright* UNKNOWN
doc/temporal_types.xml: *No copyright* UNKNOWN
doc/time_types_range_types.xml: *No copyright* UNKNOWN
doc/tnpoint_reference.xml: *No copyright* UNKNOWN
```
The file you changed `doc/mobilitydb-manual.xml` does not show any more, so it is good:
https://github.com/estebanzimanyi/MobilityDB/commit/231a00b0471f3f734e2c1bee32f92752133c91a8#diff-0aebcfc67139be551557b021de9521c3884a4884300a77b0d9e9e17577c9849e

**Comment by cvvergara** [comment]
@estebanzimanyi 
I need a favor, can you please approve this one (only approve, In pgRouting the colaborator merges their own PR):
https://github.com/pgRouting/pgrouting/pull/2023
I can not approve my own PR

**Comment by estebanzimanyi** [comment]
> I'll put my PR as draft, and un draft it when the issues are addressed

I have made all the required changes. Could you please try again ?

**Review by estebanzimanyi — APPROVED** [review]

**Pull request merged**
