### PR TITLE
Make test work locally

### PR DESCRIPTION
**Pull request by cvvergara**
This is the first PR of a series of PR
Before any change, I should be able to run tests locally on my computer.
The main issue for not been able to test locally is that `pg_ctl` (int test.sh) is not found, unless you add it to the manually to the path, now, that file is configured with the findings during the build and configured.

The tests are grouped now in directory `test`, on lack of a better name I am calling "general" the items that are not point or npoint
```
test
├── general
│   ├── data
│   ├── expected
│   └── queries
├── npoint
│   ├── data
│   ├── expected
│   └── queries
├── point
│   ├── data
│   ├── expected
│   └── queries
└── scripts
```
I can not how things went travis 
https://travis-ci.com/github/cvvergara/MobilityDB

### CODE REVIEW

**Comment by estebanzimanyi** [comment]
Many thanks for this amazing work ! 

I have one question. A traditional usage when developing a new functionality in MobilityDB is to test a single file, or a set of files satisfying a regular expression. For example, while the command
ctest 
launch all the test, the command
ctest -R 56
will only launch the tests 56_tpoint_spatialfuncs and 56_tpoint_spatialfuncs_tbl.

Is this functionality available in your PR ?

**Comment by estebanzimanyi** [comment]
In the file .github/workflows/pgversion.yml I would suggest to change the test database from ___pgr___test___ to ___mobdb___test___

**Comment by estebanzimanyi** [comment]
* In file test/scripts/CMakeLists.txt 

```
#TODO find xycat (or suitable decompressor)
set(UNCOMPRESS xycat)
```

I think xycat should be xzcat

* In files point/point.cmake and npoint/npoint.cmake we can remove

`add_definitions(-DWITH_POSTGIS)`

since this is no longer needed in the code.

* In file test/scripts/CMakeLists.txt, line 33, I think there is a typo: buid -> build

* In file test/scripts/test.sh we can remove the commented line 79, it was needed before fixing the name of the extension to mobilitydb

**Comment by cvvergara** [comment]
About:
- In files point/point.cmake and npoint/npoint.cmake we can remove `add_definitions(-DWITH_POSTGIS)`
  - At least I am not doing it at this stage, as I haven't check all the build. (and those files eventually will be 100% gone)

- In file test/scripts/test.sh we can remove the commented line 79, it was needed before fixing the name of the extension to mobilitydb
  - I still need it to test when the `\echo Use "CREATE EXTENSION mobilitydb" to load this file. \quit` line is added to make sure that the extension does not get loaded without create extension

**Comment by cvvergara** [comment]
Please let me do my own merges.
Just approve, and I'll do the merge

**Review by estebanzimanyi — APPROVED** [review]

**Comment by estebanzimanyi** [comment]
Arthur Lesuisse, our previous sysadmin, works on another department of the university. Therefore he maybe will not have time to do this review. If needed, a second review can be done by Maxime Schoemans.

**Comment by cvvergara** [comment]
In pgRouting I list many people, but when I see that it is approved by anyone, I do the merge

**Pull request merged**
